[build]
  base = "web"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # VITE_API_URL будет настроена в Netlify UI в разделе Environment Variables
  # Для локального тестирования используйте .env.local

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"